### ISSUE TITLE
which are the best management of TelegramClient?

### ISSUE THREAD

**Issue by xanscale** [badoualy/kotlogram#32]
I'm locked on callback and close. make 1 instance of TelegramClient for all application without ".close" or make 1 instance each controller that needs and close on controller destroy?
i have problem in each solution

- 1 application instance: i need callback inside controller
- 1 controller instance: when i move from 2 controller where each use TelegramClient i close first and instanziate second quickly and receive crash :(

**Comment by badoualy** [comment]
If we're talking about doing standard calls (no upload/download) I'd say keep 1 client, and you should be able to use sync method to get the result in your current thread, it should not be an issue.

If multiple controllers are in the same threads and you don't want to be blocking, then currently there's no way to do this. When I started the lib I had 2 versions of the client, one sync and another returning observable, ended up removing the latter because it was a pain to maintain 2 almost identical classes without being able to use inheritance because of one being sync and the other async. Maybe it's time I think about re-introducing an API to get the result as an `Observable`.

If you need to download/upload files, you can get a `downloaderClient` from your main client to avoid blocking your main client.

What is the crash you're mentioning? If you use multiple client and call `close()` you need to make sure you're using `close(false)` version.

**Comment by xanscale** [comment]
try to exaplain my problem:
i have 2 controller, login and chat. after login was succesfull o close login controller and open chat controller.
the flow are this:

- start login controller and inside initialize TLClient
- make login using TLClient
- close login controller, make TLClient.close() and launch chat controller
- start chat controller and inside initialize TLClient
- make some TLClient calls
- receive exception

**Comment by badoualy** [comment]
In this case I would find a way to pass your TLClient instance to your chat controller instead of closing it to re-open it.

What's the exception? How are you closing the client in the login controller? Are you using `client.close(false);` ?

**Comment by xanscale** [comment]
i recreate TLClient instance becaouse i want to change callback

whit client.close(false); works, but i don't know if is the correct way to manage TLClient

**Comment by badoualy** [comment]
I should probably set the callback as mutable, could potentially be dangerous in multi-thread use-case though, like the callback being modified while being called, but I guess that's the dev job to avoid this kind of issues.

I would think this this the clean way to do it, instead of closing a connection to re-open a new one immediately.

I'll push a commit with the callback as mutable ASAP.

**Comment by xanscale** [comment]
thz. another question about rxJava: why use rxJava if all methods are synchronous?

i think that is better to remove completely thread management inside library and make all in current thread, and demand thread management on final developer 

no?

**Comment by badoualy** [comment]
RxJava is used internally to handle threading. 
Telegram API is not synchronous, you can send multiple rpc query at once, and get the response in any order. So threading is needed. And as mentioned above, at first, I also had a client implementation that returned Observable instead of being synchronous, this way the developer could handle thread easily (that's the beauty of rx, you can use `subscribeOn` and `observeOn` to manage threading).

Everything is synchronous in the default client because the result is in fact transformed using `toBlockable` :)

So removing thread management inside library is not possible :)

**Comment by xanscale** [comment]
i suggest to remove all optional params from getDefaultClient and create setter

**Comment by badoualy** [comment]
preferredDataCenter is not optional since it's used for the first connection so cannot remove it.
The updateCallback could be removed from constructor I guess, but I find it more convenient to be able to pass it directly, and since overloads are generated, I don't see the issue in keeping it

**Comment by badoualy** [comment]
After some thinking, updateCallback should not be removed from the constructor:
The client is connecting to Telegram when created, and sometimes you'll get updates from Telegram right on connection (updates since last connection). 
If updateCallback is set via a setter only, you could lose updates.
